convert ci to csae

diff --git a/.github/workflows/ci-integration-tests-new.yml b/.github/workflows/ci-integration-tests-new.yml
--- a/.github/workflows/ci-integration-tests-new.yml
+++ b/.github/workflows/ci-integration-tests-new.yml
@@ -9,49 +9,42 @@ on:
 jobs:
   test:
     strategy:
-      max-parallel: 1
       matrix:
-        python: ['3.10', '3.11']
+        python: ['3.11']
+        # python: ['3.8', '3.9', '3.10', '3.11']
     runs-on: ubuntu-latest
     name: Functional test
     steps:
-      # - name: Start Clearscape DBS
-      #   shell: bash
-      #   run: |
-      #     curl -X 'PATCH' \
-      #       'https://api.clearscape.teradata.com/environments/dbt-teradata-1' \
-      #       -H 'accept: application/json' \
-      #       -H 'Authorization: Bearer 2OKQYw4jhaCO3T7UBLjYmsoTxs73IG9q4Ps3kZT6DpnKBKO2mLYd4k6QkGuwW9db' \
-      #       -H 'Content-Type: application/json' \
-      #       -d '{
-      #       "operation": "start"
-      #     }'
-
-      #     curl -X 'PATCH' \
-      #       'https://api.clearscape.teradata.com/environments/dbt-teradata-2' \
-      #       -H 'accept: application/json' \
-      #       -H 'Authorization: Bearer 2OKQYw4jhaCO3T7UBLjYmsoTxs73IG9q4Ps3kZT6DpnKBKO2mLYd4k6QkGuwW9db' \
-      #       -H 'Content-Type: application/json' \
-      #       -d '{
-      #       "operation": "start"
-      #     }'
-
-      #     curl -X 'PATCH' \
-      #       'https://api.clearscape.teradata.com/environments/dbt-teradata-3' \
-      #       -H 'accept: application/json' \
-      #       -H 'Authorization: Bearer 2OKQYw4jhaCO3T7UBLjYmsoTxs73IG9q4Ps3kZT6DpnKBKO2mLYd4k6QkGuwW9db' \
-      #       -H 'Content-Type: application/json' \
-      #       -d '{
-      #       "operation": "start"
-      #     }'
-        
+      - name: Define CSAE env name
+        id: define-environment-name
+        run: |
+          echo "env-name=dbt-ci-$PYTHON_VERSION-$(date +%s%N)" >> $GITHUB_OUTPUT
+        env:
+          PYTHON_VERSION: ${{ matrix.python }}
       - name: Setup Python
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python }}
       - name: Check out repository code
         uses: actions/checkout@v2
-
+      - name: Create CSAE environment
+        shell: bash
+        run: |
+          RESULT=$(curl --location --request POST 'https://api.clearscape.teradata.com/environments' \
+            --header "Authorization: Bearer $CSAE_TOKEN" \
+            --header 'Content-Type: application/json' \
+            --data-raw "{
+                \"name\": \"$CSAE_ENV_NAME\",
+                \"region\": \"us-central\",
+                \"password\": \"$CSAE_ENV_PASSWORD\",
+                \"startupScript\": \"#!/bin/bash\n\nfunction withRetry {\n  local RETRIES=$1; shift 1\n  local SLEEP=$1; shift 1\n  for i in $(seq 1 $RETRIES)\n  do\n    echo \\"Attempt $i: Running command $@\\"\n    $@ && s=0 && break || s=$? && sleep $SLEEP\n  done\n  return $s\n}\n\nfunction ensureVantageIsUp {\n  pdestate -a\n  pdestate -a | grep \\"DBS state is [45]\\"\n}\n\ndbscontrol << EOF\nm i 551=false\nEOF\ntpareset -y changing dbscontrol\nwithRetry 40 2 ensureVantageIsUp\"
+            }")
+          TERADATA_SERVER_NAME=$(echo $RESULT | jq -r '.dnsName')
+          echo "teradata-server-name=$TERADATA_SERVER_NAME" >> $GITHUB_OUTPUT
+        env:
+          CSAE_TOKEN: ${{ secrets.CSAE_TOKEN }}
+          CSAE_ENV_PASSWORD: ${{ secrets.CSAE_ENV_PASSWORD }}
+          CSAE_ENV_NAME: ${{ steps.define-environment-name.outputs.env-name}}
       - name: Install TTU
         shell: bash
         run: |
@@ -68,34 +61,34 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements_dev.txt
 
-      # - name: Prepare database
-      #   shell: bash
-      #   run: |          
-      #     export PATH=$PATH:"/opt/teradata/client/17.20/bin"
+      - name: Prepare database
+        shell: bash
+        run: |
+          export PATH=$PATH:"/opt/teradata/client/17.20/bin"
 
-      #     cd md5_20080530/md5/src
+          cd md5_20080530/md5/src
 
-      #     # prepare bteq script
-      
-      #     cat << EOF > /tmp/install_md5.bteq
+          # prepare bteq script
 
-      #     .SET EXITONDELAY ON MAXREQTIME 20
-      #     .logon $DBT_TERADATA_SERVER_NAME/$DBT_TERADATA_USERNAME,$DBT_TERADATA_PASSWORD
-      #     CREATE DATABASE GLOBAL_FUNCTIONS AS PERMANENT = 60e6, SPOOL = 120e6;
-      #     GRANT CREATE FUNCTION ON GLOBAL_FUNCTIONS TO $DBT_TERADATA_USERNAME;
-      #     DATABASE GLOBAL_FUNCTIONS;
-      #     .run file = hash_md5.btq
-      #     GRANT EXECUTE FUNCTION ON GLOBAL_FUNCTIONS TO PUBLIC WITH GRANT OPTION;
-      #     .logoff
-      #     EOF
+          cat << EOF > /tmp/install_md5.bteq
 
-      #     bteq < /tmp/install_md5.bteq
-      #   env:
-      #     DBT_TERADATA_SERVER_NAME: ${{ vars.DBT_TERADATA_SERVER_NAME }}
-      #     DBT_TERADATA_USERNAME: ${{ vars.DBT_TERADATA_USERNAME }}
-      #     DBT_TERADATA_PASSWORD: ${{ vars.DBT_TERADATA_PASSWORD }}
+          .SET EXITONDELAY ON MAXREQTIME 20
+          .logon $DBT_TERADATA_SERVER_NAME/$DBT_TERADATA_USERNAME,$DBT_TERADATA_PASSWORD
+          CREATE DATABASE GLOBAL_FUNCTIONS AS PERMANENT = 60e6, SPOOL = 120e6;
+          GRANT CREATE FUNCTION ON GLOBAL_FUNCTIONS TO $DBT_TERADATA_USERNAME;
+          DATABASE GLOBAL_FUNCTIONS;
+          .run file = hash_md5.btq
+          GRANT EXECUTE FUNCTION ON GLOBAL_FUNCTIONS TO PUBLIC WITH GRANT OPTION;
+          .logoff
+          EOF
 
-          
+          bteq < /tmp/install_md5.bteq
+        env:
+          DBT_TERADATA_SERVER_NAME: ${{ steps.start-test-environment.outputs.teradata-server-name }}
+          DBT_TERADATA_USERNAME: demo_user
+          DBT_TERADATA_PASSWORD: ${{ secrets.CSAE_ENV_PASSWORD }}
+
+
       - name: Run pytest tests
         run: |
           sed -i "s/localhost/$DBT_TERADATA_SERVER_NAME/g" tests/conftest.py
@@ -106,11 +99,11 @@ jobs:
           export DBT_TEST_USER_3=test_grants_user3
           pytest -v -k "not TestCurrentTimestamp" tests/functional
         env:
-          DBT_TERADATA_SERVER_NAME: ${{ vars.DBT_TERADATA_SERVER_NAME }}
-          DBT_TERADATA_USERNAME: ${{ vars.DBT_TERADATA_USERNAME }}
-          DBT_TERADATA_PASSWORD: ${{ vars.DBT_TERADATA_PASSWORD }}
+          DBT_TERADATA_SERVER_NAME: ${{ steps.start-test-environment.outputs.teradata-server-name }}
+          DBT_TERADATA_USERNAME: demo_user
+          DBT_TERADATA_PASSWORD: ${{ secrets.CSAE_ENV_PASSWORD }}
 
-      - name: Run performance tests for fastload
+      - name: Setup environment for performance and catalog tests
         run: |
           mkdir ~/.dbt
           cat << EOF > ~/.dbt/profiles.yml
@@ -141,23 +134,26 @@ jobs:
                 priority: interactive
                 retries: 1
           EOF
+        env:
+          DBT_TERADATA_SERVER_NAME: ${{ steps.start-test-environment.outputs.teradata-server-name }}
+          DBT_TERADATA_USERNAME: demo_user
+          DBT_TERADATA_PASSWORD: ${{ secrets.CSAE_ENV_PASSWORD }}
+          DBT_TERADATA_SERVER_NAME_1: ${{ steps.start-test-environment.outputs.teradata-server-name }}
+          DBT_TERADATA_USERNAME_1: demo_user
+          DBT_TERADATA_PASSWORD_1: ${{ secrets.CSAE_ENV_PASSWORD }}
+
+      - name: Run performance tests
+        run: |
           cd $GITHUB_WORKSPACE/test/performance
           ./run.sh
-        env:
-          DBT_TERADATA_SERVER_NAME: ${{ vars.DBT_TERADATA_SERVER_NAME }}
-          DBT_TERADATA_USERNAME: ${{ vars.DBT_TERADATA_USERNAME }}
-          DBT_TERADATA_PASSWORD: ${{ vars.DBT_TERADATA_PASSWORD }}
-          DBT_TERADATA_SERVER_NAME_1: ${{ vars.DBT_TERADATA_SERVER_NAME_1 }}
-          DBT_TERADATA_USERNAME_1: ${{ vars.DBT_TERADATA_USERNAME_1 }}
-          DBT_TERADATA_PASSWORD_1: ${{ vars.DBT_TERADATA_PASSWORD_1 }}
-        
+
       - name: Run catalog tests
         run: |
           cd $GITHUB_WORKSPACE/test/catalog/with_qvci
           ./run.sh
           cd $GITHUB_WORKSPACE/test/catalog/without_qvci
           ./run.sh
-      
+
       - name: Run nopi tests
         run: |
           sed -i "s/hostname=dbt.*/hostname='$DBT_TERADATA_SERVER_NAME_2'/g" tests/conftest.py
@@ -165,43 +161,15 @@ jobs:
           sed -i "s/password=dbt.*/password='$DBT_TERADATA_PASSWORD_2'/g" tests/conftest.py
           pytest tests/functional/adapter/test_nopi.py
         env:
-          DBT_TERADATA_SERVER_NAME_2: ${{ vars.DBT_TERADATA_SERVER_NAME_2 }}
-          DBT_TERADATA_USERNAME_2: ${{ vars.DBT_TERADATA_USERNAME_2 }}
-          DBT_TERADATA_PASSWORD_2: ${{ vars.DBT_TERADATA_PASSWORD_2 }}
+          DBT_TERADATA_SERVER_NAME: ${{ steps.start-test-environment.outputs.teradata-server-name }}
+          DBT_TERADATA_USERNAME: demo_user
+          DBT_TERADATA_PASSWORD: ${{ secrets.CSAE_ENV_PASSWORD }}
 
-      # - name: Stop Clearscape DBS
-      #   if: always()
-      #   shell: bash
-      #   run: |
-      #     curl -X 'PATCH' \
-      #       'https://api.clearscape.teradata.com/environments/dbt-teradata-1' \
-      #       -H 'accept: application/json' \
-      #       -H 'Authorization: Bearer 2OKQYw4jhaCO3T7UBLjYmsoTxs73IG9q4Ps3kZT6DpnKBKO2mLYd4k6QkGuwW9db' \
-      #       -H 'Content-Type: application/json' \
-      #       -d '{
-      #       "operation": "stop"
-      #     }'
-
-      #     curl -X 'PATCH' \
-      #       'https://api.clearscape.teradata.com/environments/dbt-teradata-2' \
-      #       -H 'accept: application/json' \
-      #       -H 'Authorization: Bearer 2OKQYw4jhaCO3T7UBLjYmsoTxs73IG9q4Ps3kZT6DpnKBKO2mLYd4k6QkGuwW9db' \
-      #       -H 'Content-Type: application/json' \
-      #       -d '{
-      #       "operation": "stop"
-      #     }'
-
-      #     curl -X 'PATCH' \
-      #       'https://api.clearscape.teradata.com/environments/dbt-teradata-3' \
-      #       -H 'accept: application/json' \
-      #       -H 'Authorization: Bearer 2OKQYw4jhaCO3T7UBLjYmsoTxs73IG9q4Ps3kZT6DpnKBKO2mLYd4k6QkGuwW9db' \
-      #       -H 'Content-Type: application/json' \
-      #       -d '{
-      #       "operation": "stop"
-      #     }'
-          
-      - uses: actions/upload-artifact@v2
-        if: ${{ failure() ||  cancelled() }}
-        with:
-          name: virtualbox-logs
-          path: /Users/runner/VirtualBox*
+      - name: Delete CSAE environment
+        if: always()
+        run: |
+          curl --location --request DELETE "https://api.clearscape.teradata.com/environments/$CSAE_ENV_NAME" \
+            --header "Authorization: Bearer $CSAE_TOKEN"
+        env:
+          CSAE_TOKEN: '${{ secrets.CSAE_TOKEN }}'
+          CSAE_ENV_NAME: '${{ steps.define-environment-name.outputs.env-name}}'
